# Chapter 2

### Python Basics

In [7]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


The following command provides info about print() function

In [10]:
print?

Adding two numbers

In [9]:
3 + 5

8

String concatenation using +

In [11]:
"hello" + " " + "world"

'hello world'

Lists

In [12]:
x = [3, 4, 5]
x

[3, 4, 5]

Let's try to add the two sets element by element, but instead the + operator concatenates the two lists.

In [13]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

### Introduction to Numerical Python (Numpy)

In [1]:
import numpy as np

Numpy 1-D array also known as vector

In [2]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

Adding two numpy arrays

In [3]:
x + y

array([ 7, 13, 12])

Numpy 2-D also known as Matrix

In [5]:
x = np.array([
    [1, 2],
    [3, 4]
])
x

array([[1, 2],
       [3, 4]])

Here this x has several attributes, some of them are ndim, dtype etc

In [9]:
x.ndim

2

In [10]:
x.dtype

dtype('int32')

In [11]:
np.array([
    [1, 2],
    [3.0, 4]
]).dtype

dtype('float64')

In [14]:
np.array?

We can pass dtype as argument in np.array() as well

In [15]:
np.array([
    [1, 2],
    [3, 4]
], float).dtype

dtype('float64')

In [19]:
x.shape

(2, 2)

Some methods of numpy arrays, eg: sum() - It sums up all the elements of the array.

In [20]:
x = np.array([1, 2, 3, 4])
x.sum()

10

Another way to do the same thing is to pass x as an argument

In [22]:
x = np.array([3, 4, 5, 6, 7])
np.sum(x)

25

reshape() method, it changes the shape (dimensions) of the array, according to our requirement

In [38]:
x = np.array([1, 2, 3, 4, 5, 6])
print(f'beggining x:\n {x}')
x_reshape = x.reshape((2, 3))
print(f'reshaped x:\n {x_reshape}')

beggining x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


Accessing elements from an array

In [39]:
x_reshape[0, 0]

1

In [40]:
x_reshape[1, 2]

6

Now, let’s modify the top left element of x_reshape. To our surprise, we
discover that the frst element of x has been modifed as well!

In [41]:
print("x before we modify x_reshape:\n", x)
print("x_reshape before we modify x_reshape:\n", x_reshape)
x_reshape[0, 0] = 5
print("x_reshape after we modify its top left element:\n", x_reshape)
print("x after we modify top left element of x_reshape:\n", x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


*Modifying x_reshape also modifed x because the two objects occupy the
same space in memory.*

Tuples are immutable

In [42]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

Some important attributes

In [43]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [46]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [47]:
x**2

array([25,  4,  9, 16, 25, 36])

In [48]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [49]:
np.random.normal?

We now generate 50 independent random variables from a N(0, 1) distribution.

In [51]:
x = np.random.normal(size=50)
x

array([ 4.09763549e-01,  1.10177257e+00, -8.52447246e-01,  8.80585744e-01,
       -2.17471829e+00, -6.33110851e-01, -3.81181598e-01, -1.11535081e+00,
        2.10707716e-01, -8.79054967e-01, -5.24203908e-01,  1.89079237e-01,
       -6.34890995e-02,  5.61271134e-01,  2.75517094e-01,  2.14968466e-02,
       -3.53242839e-01,  1.51258537e-01, -5.30249526e-01,  1.84259253e+00,
       -1.93325053e+00, -4.21185069e-01, -4.81430775e-01,  1.79227787e+00,
       -3.93053066e-01,  1.74522486e+00,  8.02933806e-01,  3.15798325e-01,
        4.23007347e-01,  4.35534011e-01,  7.23754820e-01, -9.04152376e-01,
        1.24003525e-03,  1.51421066e+00, -6.22577189e-01, -5.85873871e-01,
        8.05003273e-01,  3.47864001e-01,  1.51702631e-01,  6.16509717e-01,
        4.14122821e-01, -9.82861313e-02,  1.88114165e+00,  8.44314387e-01,
       -1.01567299e+00, -5.87815915e-02, -5.13566798e-01, -1.52863165e+00,
        5.41803386e-02,  7.24894895e-02])

We create an array y by adding an independent N(50, 1) random variable
to each element of x.

In [52]:
y = x + np.random.normal(loc=50, scale=1, size=50)
y

array([50.70452103, 50.51667878, 48.78195539, 50.47618851, 47.59517846,
       50.00378568, 48.8830633 , 48.27656137, 51.02182779, 48.08551527,
       48.38129789, 50.89687804, 51.34986864, 50.55894788, 52.53076294,
       50.11083433, 48.93577934, 49.81877413, 48.85601168, 51.13613117,
       48.42316512, 48.99364288, 47.80970095, 52.50730975, 51.43250713,
       49.75254327, 49.4461559 , 51.32923636, 51.25074535, 52.62942014,
       49.95939802, 49.70796075, 49.84516512, 49.95263461, 49.45289757,
       49.97137616, 50.16577215, 48.25192632, 49.05816318, 50.56022075,
       49.9013527 , 49.46307383, 51.63640542, 50.66624324, 49.13781378,
       50.13610913, 49.38069574, 47.35191133, 49.01251697, 51.82265923])

The np.corrcoef() function computes the correlation matrix between x and
y. The off-diagonal elements give the correlation between x and y.

In [54]:
np.corrcoef(x, y)

array([[1.        , 0.63330465],
       [0.63330465, 1.        ]])

We get different results, when calling random.normal() each time

In [55]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))

[-5.3126811  13.95960862]
[2.87948914 1.73082585]


But, if we want to get the same data in second or consecutive random calls, then we can set the random seed using the np.random.default_rng() function.
This function takes an arbitrary, user-specifed integer argument.

In [60]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


The np.mean(), np.var(), and np.std() functions can be used to compute
the mean, variance, and standard deviation of arrays. These functions are
also available as methods on the arrays.

In [64]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()  # We can write in both ways

(-0.1126795190952861, -0.1126795190952861)

In [65]:
np.var(y), y.var(), np.mean((y - y.mean()) ** 2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [66]:
np.sqrt(np.var(y)), np.std(y)

(1.6505576756498128, 1.6505576756498128)

The np.mean(), np.var(), and np.std() functions can also be applied to the
rows and columns of a matrix.

In [67]:
X = rng.standard_normal((10, 3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [68]:
X.mean(axis=0) # means row = 0 (since arrays are row-major ordered)

array([ 0.15030588,  0.14030961, -0.34238602])

In [69]:
X.mean(0) # This also gives the same result

array([ 0.15030588,  0.14030961, -0.34238602])