# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

In [3]:
jovian.commit(project='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.com/ ):
API KEY: ········
[jovian] Creating a new project "wasif1607/100-numpy-exercises"
[jovian] Committed successfully! https://jovian.com/wasif1607/100-numpy-exercises


'https://jovian.com/wasif1607/100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [1]:
# Ucomment the next line if you need install numpy
!pip install numpy --upgrade

                                              0.0/15.0 MB ? eta -:--:--
                                             0.0/15.0 MB 991.0 kB/s eta 0:00:16
                                              0.1/15.0 MB 1.0 MB/s eta 0:00:15
                                              0.2/15.0 MB 1.1 MB/s eta 0:00:15
                                              0.2/15.0 MB 1.3 MB/s eta 0:00:12
                                              0.3/15.0 MB 1.3 MB/s eta 0:00:12
     -                                        0.4/15.0 MB 1.3 MB/s eta 0:00:11
     -                                        0.5/15.0 MB 1.3 MB/s eta 0:00:11
     -                                        0.5/15.0 MB 1.3 MB/s eta 0:00:12
     -                                        0.5/15.0 MB 1.2 MB/s eta 0:00:13
     -                                        0.5/15.0 MB 1.2 MB/s eta 0:00:13
     -                                        0.5/15.0 MB 1.2 MB/s eta 0:00:13
     -                                        0.7/15.0 MB 

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\conda7\\envs\\100-numpy-exercises\\Lib\\site-packages\\~umpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll'
Consider using the `--user` option or check the permissions.



#### 1. Import the numpy package under the name `np` (★☆☆)

In [17]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [18]:
pip show numpy

Name: numpy
Version: 1.25.0
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: D:\conda7\envs\100-numpy-exercises\Lib\site-packages
Requires: 
Required-by: 
Note: you may need to restart the kernel to use updated packages.


#### 3. Create a null vector of size 10 (★☆☆)

In [19]:
k = np.zeros(10)  #######
k

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [20]:
print(f"Size of the array {k.size}")
print(f"Size of an element in array {k.itemsize}")
print(f"Memory size of an array {k.size * k.itemsize}")

Size of the array 10
Size of an element in array 8
Memory size of an array 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [21]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [22]:
k[4] = 1
k

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
np.arange(10,50)  #######

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [24]:
rev = np.array([1,2,3,4,5,6,7])
rev[-1: : -1]

array([7, 6, 5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
np.arange(0, 9).reshape(3,3)  #######

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [26]:
chk = np.array([1,2,0,0,4,0])

# MINE
for i, v in enumerate(chk):
    if v:
        print(i)
        
# BETTER
np.nonzero(chk)  #######

0
1
4


(array([0, 1, 4], dtype=int64),)

Save your progress by commiting your work to Jovian

In [13]:
import jovian

In [14]:
jovian.commit(project='numpy-100-exercises')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "wasif1607/numpy-100-exercises" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/wasif1607/numpy-100-exercises


'https://jovian.com/wasif1607/numpy-100-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [27]:
np.identity(3)  #######

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [28]:
np.random.random((3,3,3))  #######

array([[[0.32112002, 0.52145257, 0.62284435],
        [0.33823173, 0.32049152, 0.62660039],
        [0.47433285, 0.31010708, 0.53202141]],

       [[0.26508779, 0.70501214, 0.6706697 ],
        [0.32738131, 0.11829004, 0.10330658],
        [0.53976045, 0.26676452, 0.56341521]],

       [[0.90959023, 0.55793572, 0.51704756],
        [0.4361703 , 0.72932784, 0.61944327],
        [0.47726505, 0.0604747 , 0.59612757]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
das = np.random.random((10,10))
print(das)
print(f"Maximum: {das.max()}")  #######
print(f"Minimum: {das.min()}")  #######

[[0.78205454 0.08242308 0.69989257 0.9174305  0.53696905 0.97952313
  0.38606197 0.41665254 0.01495003 0.31194954]
 [0.25795248 0.51137532 0.66918313 0.73471512 0.11979334 0.40434717
  0.35014467 0.16598539 0.30024178 0.33767879]
 [0.93475487 0.7281155  0.51964684 0.81064245 0.98265774 0.07942578
  0.22631816 0.27996836 0.74203488 0.02482658]
 [0.48717224 0.29533155 0.26695953 0.69233098 0.94184976 0.48770732
  0.83963887 0.48450482 0.41941138 0.49561494]
 [0.83198668 0.01339507 0.75824366 0.37652078 0.76627419 0.19707502
  0.01913567 0.26220523 0.36147074 0.3484574 ]
 [0.36806506 0.07896056 0.32041857 0.28267988 0.13932603 0.81921261
  0.27814865 0.76602171 0.04715896 0.70715856]
 [0.82532314 0.74410794 0.81369801 0.65768614 0.15457314 0.11553318
  0.60814502 0.85681257 0.1112565  0.21181065]
 [0.25159764 0.80037399 0.95923815 0.00592474 0.63428843 0.29286252
  0.44608276 0.88549272 0.71705975 0.69256433]
 [0.24093232 0.1756042  0.93615586 0.65863697 0.84848716 0.32971204
  0.51648674

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
men = np.random.random(30)
print(f"Mean value is: {men.mean()}")  #######

Mean value is: 0.4295644183589535


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [31]:
lol = np.zeros((2, 3))
lol[0, 0] = lol[-1, -1] = 1
lol

array([[1., 0., 0.],
       [0., 0., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [32]:
krte = np.random.random((3,3))
np.pad(krte, pad_width=1, mode="constant", constant_values=0)  #######

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.19229985, 0.33680364, 0.60378353, 0.        ],
       [0.        , 0.79765081, 0.8523457 , 0.98288249, 0.        ],
       [0.        , 0.503972  , 0.85733439, 0.00328498, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [33]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [34]:
a=np.diag((1,2,3,4), k = -1)  # k = -1 mtlb diagonal ki ek neeche wali line
# Another approach
b = np.diag(np.arange(1, 5), k = -1)  #######
print(f"Simple: \n{a}\n")
print(f"arange: \n{b}")

Simple: 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

arange: 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [35]:
board = np.ones((8, 8), dtype="int")  #######
# 1st row, 0th col (1,0) to last skipping 1
board[1::2, ::2]= 0
# 0th row, 1st col (0,1) to last skipping 1
board[::2, 1::2] = 0
board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [36]:
np.unravel_index(100, (6,7,8))  #######

(1, 5, 4)

Save your progress by commiting your work to Jovian

In [25]:
import jovian

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "wasif1607/numpy-100-exercises" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/wasif1607/numpy-100-exercises


'https://jovian.com/wasif1607/numpy-100-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [37]:
temp = np.array([[0,1],
                 [1,0]])
np.tile(temp, (4,4))  #######

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [38]:
norm = np.random.random((5,5))
print(f"Original array: \n{norm}")
maxi, mini = norm.max(), norm.min()
norm = (norm - mini)/(maxi - mini)
print(f"Normalized array: \n{norm}")

Original array: 
[[0.28964695 0.61136719 0.32728765 0.23187838 0.8702343 ]
 [0.99383693 0.65527956 0.01175051 0.53562371 0.37676284]
 [0.90789186 0.69661375 0.76404357 0.82664216 0.42615399]
 [0.47521903 0.74451806 0.76929288 0.35108472 0.07909692]
 [0.55937931 0.42281478 0.30663674 0.88470245 0.84671171]]
Normalized array: 
[[0.28296536 0.61055389 0.32129264 0.22414307 0.87414282]
 [1.         0.65526723 0.         0.53342882 0.37167027]
 [0.91248727 0.69735538 0.76601513 0.82975555 0.42196233]
 [0.47192234 0.74613348 0.7713602  0.34552377 0.06857482]
 [0.55761773 0.41856222 0.30026505 0.88887487 0.85019117]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [39]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])  #######
print(RGBA)
color = np.array((1,2,4,3),dtype = RGBA)
print(color)
print((color['blue']))
type(color)

[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]
(1, 2, 4, 3)
4


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [40]:
a = np.arange(0, 30, 2).reshape(5,3)
print("a: \n", a)
b = np.arange(0, 12, 2).reshape(3, 2)
print("b: \n", b)

ans = a @ b  ####### # or we can use np.matmul(a,b)
print("ans: \n", ans)

a: 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]
b: 
 [[ 0  2]
 [ 4  6]
 [ 8 10]]
ans: 
 [[ 40  52]
 [112 160]
 [184 268]
 [256 376]
 [328 484]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
hehe = np.arange(1,10)
print(hehe >= 3)  # No need of for loop in numpy, it will return an array of True and False
print(hehe[(hehe>=3) & (hehe<=8)])
hehe[(hehe>=3) & (hehe<=8)] *= (-1)
print(hehe)

[False False  True  True  True  True  True  True  True]
[3 4 5 6 7 8]
[ 1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [42]:
print(sum(range(5),-1))  # sum(iterable, starting)
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [43]:
Z = np.arange(1,7)
print(Z)
print(Z ** Z)  # LEGAL
print(2 << Z >> 2)  # LEGAL
print(Z <- Z)  # LEGAL
print(1j * Z)  # LEGAL
print(Z / 1 / 1)  # LEGAL
print(Z < Z > Z)  # ILLEGAL

[1 2 3 4 5 6]
[    1     4    27   256  3125 46656]
[ 1  2  4  8 16 32]
[False False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j]
[1. 2. 3. 4. 5. 6.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [46]:
print(np.array(0)/np.array(0))  # nan
print(np.array(0) // np.array(0))  # 0
print(np.array([np.nan]).astype(int).astype(float))  # [-2.14748365e+09]

nan
0
[-2.14748365e+09]


C:\Users\91831\AppData\Local\Temp\ipykernel_7716\1639629202.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))  # nan
C:\Users\91831\AppData\Local\Temp\ipykernel_7716\1639629202.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))  # 0
C:\Users\91831\AppData\Local\Temp\ipykernel_7716\1639629202.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))  # [-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [45]:
arr = np.random.random((3,4))
print(arr)
arr = np.round(arr, 2)  #######  # 2 decimal places here
print(arr)

[[0.27351819 0.62427628 0.76502607 0.80465928]
 [0.29497067 0.89959839 0.41656351 0.27860815]
 [0.43173337 0.27925976 0.15635624 0.92759398]]
[[0.27 0.62 0.77 0.8 ]
 [0.29 0.9  0.42 0.28]
 [0.43 0.28 0.16 0.93]]


#### 30. How to find common values between two arrays? (★☆☆)

In [44]:
a = np.arange(0, 15, 2).reshape(4,2)
print(a)
b = np.arange(0, 22, 3).reshape(2,4)
print(b)
print(np.intersect1d(a, b))  #######

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]
[[ 0  3  6  9]
 [12 15 18 21]]
[ 0  6 12]


Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [47]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all="ignore")  ####### # Seterr function comes handy for control of warnings.
# Here all='ignore' helps in ignoring any type of warnings we might encounter.
np.nanmedian(data, axis=[1, 2])  # This statement bascially triggers a warning.

C:\Users\91831\AppData\Local\Temp\ipykernel_7716\2584743330.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmedian(data, axis=[1, 2])  # This statement bascially triggers a warning.


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
print(np.sqrt(-1))  #######
print(np.emath.sqrt(-1))  #######
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [49]:
today = np.datetime64("today", "D")  #######
print("Today ", today)
yesterday = np.datetime64("today", "D") - np.timedelta64(1, "D")  #######
print("Yesterday ", yesterday)
tomorrow = np.datetime64("today", "D") + np.timedelta64(1, "D")
print("Tomorrow", tomorrow)

Today  2023-06-18
Yesterday  2023-06-17
Tomorrow 2023-06-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [50]:
print("July 2016")
print(np.arange("2016-07", "2016-08", dtype="datetime64[D]"))  #######

July 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [51]:
A = np.ones(3)*1
print(A)
B = np.ones(3)*2
print(B)
C = np.ones(3)*3
print(C)
print(np.add(A,B,out=B))  ####### # Here, B doesn't forms a copy it gets changed in place
print(np.divide(A,2,out=A))  #######
print(np.negative(A,out=A))  #######
print(np.dot(A,B))  #######

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
-4.5


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [52]:
Z = np.random.uniform(0.5, 13.3, (5,5))  ####### # To generate random no's from given range
print(Z)
print(Z - Z % 1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print (Z.astype(int))  #######

[[ 3.19666228  7.11645536 10.38964438 13.19278051 10.55906638]
 [ 5.40701286  6.67322945  9.23366234  2.81433935  3.42123284]
 [ 5.34716252 11.67630065  8.58298865  4.69002056  5.48770527]
 [ 2.87610035  4.22133593 11.05930599  4.90270279  2.75051899]
 [ 2.56689767  1.8914546   7.32434821 12.94340053  9.34295824]]
[[ 3.  7. 10. 13. 10.]
 [ 5.  6.  9.  2.  3.]
 [ 5. 11.  8.  4.  5.]
 [ 2.  4. 11.  4.  2.]
 [ 2.  1.  7. 12.  9.]]
[[ 3.  7. 10. 13. 10.]
 [ 5.  6.  9.  2.  3.]
 [ 5. 11.  8.  4.  5.]
 [ 2.  4. 11.  4.  2.]
 [ 2.  1.  7. 12.  9.]]
[[ 3.  7. 10. 13. 10.]
 [ 5.  6.  9.  2.  3.]
 [ 5. 11.  8.  4.  5.]
 [ 2.  4. 11.  4.  2.]
 [ 2.  1.  7. 12.  9.]]
[[ 3  7 10 13 10]
 [ 5  6  9  2  3]
 [ 5 11  8  4  5]
 [ 2  4 11  4  2]
 [ 2  1  7 12  9]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [53]:
new = np.zeros((5, 5))
print(new)
new += np.arange(5)
print(new)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [54]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)  ####### # -1 == 10 here, -1 means ki last element tak jaana hai
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [55]:
# np.random.uniform(0, 1, 10)
Z = np.linspace(0, 1, 11, endpoint=False)[1:]  ####### # [1:] to exclude first element (0 here), endpoint=False to print more decimal places
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [56]:
k = np.random.random(10)
k.sort() #######
print(k)

[0.09048687 0.23087432 0.30088757 0.40840379 0.64667726 0.68140444
 0.71237282 0.75414925 0.84586762 0.93191924]


Save your progress by commiting your work to Jovian

In [145]:
import jovian

In [146]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "wasif1607/numpy-100-exercises" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/wasif1607/numpy-100-exercises


'https://jovian.com/wasif1607/numpy-100-exercises'

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [57]:
import functools as ft
Z = np.arange(5)
# np.add.reduce(Z)  #######
ft.reduce(np.add,Z,0)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [58]:
A = np.random.randint(0,2,5)  #######
B = np.random.randint(0,2,5)
print(A)
print('*'*60)
print(B)
print('*'*60)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)  #######
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)  #######
print(equal)

[0 1 0 0 1]
************************************************************
[1 0 0 0 1]
************************************************************
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [59]:
Z = np.zeros(10)
Z.flags.writeable = False  #######
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [60]:
z= np.random.randint(0,9,(10,2))
print("z: ", z)
x,y = z[:,0], z[:,1]
print("x: ", x)
print("y: ", y)
r = np.sqrt(x**2+y**2)  #######
print("r: ", r)
"""The numpy.arctan2() method computes element-wise arc tangent of arr1/arr2 choosing the quadrant correctly.
The quadrant is chosen so that arctan2(x1, x2) is the signed angle in radians between the ray ending at theorigin
and passing through the point (1, 0), and the ray ending at the origin and passing through the point (x2, x1)."""
t = np.arctan2(y,x)
print("t: ", t)
"""np.c_ takes two arrays and concatenate them coulmn-wise making them 2-D"""
poles = np.c_[r,t]
print(poles)

z:  [[3 7]
 [8 8]
 [3 4]
 [2 7]
 [0 6]
 [5 0]
 [5 3]
 [0 4]
 [0 2]
 [8 5]]
x:  [3 8 3 2 0 5 5 0 0 8]
y:  [7 8 4 7 6 0 3 4 2 5]
r:  [ 7.61577311 11.3137085   5.          7.28010989  6.          5.
  5.83095189  4.          2.          9.43398113]
t:  [1.16590454 0.78539816 0.92729522 1.29249667 1.57079633 0.
 0.5404195  1.57079633 1.57079633 0.55859932]
[[ 7.61577311  1.16590454]
 [11.3137085   0.78539816]
 [ 5.          0.92729522]
 [ 7.28010989  1.29249667]
 [ 6.          1.57079633]
 [ 5.          0.        ]
 [ 5.83095189  0.5404195 ]
 [ 4.          1.57079633]
 [ 2.          1.57079633]
 [ 9.43398113  0.55859932]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [61]:
t = np.random.randint(1,10, 7)  # 1 to 10 is range seletion of random no, and 7 is size in 1D
print(t)
print(t.argmax())  ####### # Gives index of max value
t[t.argmax()] = 0
print(t)

[7 3 9 9 9 8 3]
2
[7 3 0 9 9 8 3]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [62]:
#### DON'T KNOW
Z = np.zeros((10,10), [('x',float),('y',float)])
print("Z: \n", Z)
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(Z)

Z: 
 [[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
[[(0.        , 0.        ) (0.11111111, 0.  

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [63]:
### DON'T KNOW (WRONG)
X = np.random.randint(1,10, (2,3))
print("X: \n", X)
Y = np.random.randint(1,10, (2,3))
print("Y: \n", Y)
# C = 1 / (X - Y)
# print(C)

X: 
 [[3 4 8]
 [4 4 5]]
Y: 
 [[4 6 5]
 [6 4 5]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [64]:
for dtype in [np.int8, np.int32, np.int64]:
    print(dtype)
    print(np.iinfo(dtype).min)  #######
    print(np.iinfo(dtype).max)
    print("")
for dtype in [np.float32, np.float64]:
    print(dtype)
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    print("")

<class 'numpy.int8'>
-128
127

<class 'numpy.int32'>
-2147483648
2147483647

<class 'numpy.int64'>
-9223372036854775808
9223372036854775807

<class 'numpy.float32'>
-3.4028235e+38
3.4028235e+38
1.1920929e-07

<class 'numpy.float64'>
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16



#### 49. How to print all the values of an array? (★★☆)

In [65]:
Z = []
print(Z)

[]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [66]:
arr = np.random.uniform(0,10,10)
print("Array: ", arr)
scal = 5
print("We have to find closest value to: ", scal)
arr_1 = np.abs(arr - 5)  #######
print("Abs of array values - 5, ", arr_1)
ind = arr_1.argmin()  # Minimum value index of arr_1 array
print('*'*60)
print(arr[ind])

Array:  [2.3572309  9.87500789 7.52929868 6.36414183 8.77613812 3.4549498
 3.51316138 3.26483176 7.68228152 5.93196033]
We have to find closest value to:  5
Abs of array values - 5,  [2.6427691  4.87500789 2.52929868 1.36414183 3.77613812 1.5450502
 1.48683862 1.73516824 2.68228152 0.93196033]
************************************************************
5.931960327219443


Save and commit your work.

In [107]:
import jovian

In [108]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "wasif1607/numpy-100-exercises" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/wasif1607/numpy-100-exercises


'https://jovian.com/wasif1607/numpy-100-exercises'

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [67]:
Z = np.zeros(10, [ ('position', [ ('x', float), ('y', float)]),
                   ('color',    [ ('r', float), ('g', float),('b', float)])
                 ])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [72]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [78]:
arr = np.random.random((100,2))
print("Array: \n", arr)
X,Y = np.atleast_2d(arr[:,0],arr[:,1])  ####### # This line separates the two columns of a into two 1D arrays 
# and converts them into 2D arrays with shape (10,1)
print("X: \n", X)
print("Y: \n", Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)  ####### # x-x.T and y-y.T compute the difference between all pairs of x and y coordinates,
# respectively. Since x and y have shape (10,1), subtracting their transposes (with shape (1,10)) results in broadcasting,
# producing two 10x10 arrays where each element represents the difference in x or y coordinates between a pair of points.
print("D: \n", D)
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

Array: 
 [[0.41836091 0.9581132 ]
 [0.03945938 0.51982721]
 [0.3518397  0.71602857]
 [0.39752173 0.38192932]
 [0.98325331 0.47646913]
 [0.93303606 0.56266107]
 [0.5449319  0.37402476]
 [0.88310584 0.26456969]
 [0.05718769 0.86480759]
 [0.18216988 0.5560758 ]
 [0.35607772 0.26862335]
 [0.7045532  0.42213916]
 [0.43196073 0.90542597]
 [0.10684771 0.14244649]
 [0.16355119 0.5130511 ]
 [0.84279052 0.72316068]
 [0.60259116 0.97531715]
 [0.2033809  0.08273607]
 [0.83937205 0.24256616]
 [0.04209657 0.593126  ]
 [0.69228245 0.62384951]
 [0.20453945 0.51283649]
 [0.89694683 0.76018535]
 [0.87512491 0.16976113]
 [0.42239251 0.33620023]
 [0.82382703 0.84712865]
 [0.43588068 0.49703275]
 [0.44255438 0.01001055]
 [0.39632193 0.73922596]
 [0.50280319 0.73389299]
 [0.14723135 0.94699349]
 [0.00702094 0.84330936]
 [0.7662779  0.5268239 ]
 [0.74287758 0.03231199]
 [0.26445219 0.95976751]
 [0.90238708 0.69931003]
 [0.01700816 0.5500965 ]
 [0.08772082 0.22577815]
 [0.56754812 0.68326058]
 [0.98677333 0.0

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [86]:
Z = np.arange(10, dtype=np.float32)
print("Initial: \n", Z)
Z_1 = Z.astype(np.float32, copy=False)  #######
Z_1[0] = 2
print("Final: \n", Z)

Initial: 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Final: 
 [2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [89]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int64)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [95]:
Z = np.arange(9).reshape(3,3)
print("Z: \n", Z)
print("\nFrom ndenumerate:")
for index, value in np.ndenumerate(Z):  ####### # Works like enumerate of python
    print(index, value)
print("\nFrom ndindex:")
for index in np.ndindex(Z.shape):  #######
    print(index, Z[index])

Z: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

From ndenumerate:
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

From ndindex:
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [100]:
sigma,myu = 1.0,0.0

# Creates a 2-D mesh
X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
print("X: \n", X)
print("Y: \n", Y)
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2)) # e^-((x^2 + y^2)^1/2 - 0.0)^2 / (2 * 1.0^2)
print("G: \n", G)

X: 
 [[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.     

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [108]:
n = 10
p = 3
Z = np.zeros((n,n))
print("Z: \n", Z)
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)  #######
print("Z with randomly placed no.s: \n", Z)


Z: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Z with randomly placed no.s: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [113]:
X = np.random.rand(5, 10)
print("X: \n", X)
Y = X - X.mean(axis = 1,keepdims = True)  #######
print("Y: \n", Y)
K = X.mean(axis = 1).reshape(-1,1)
print("K: \n", K)
M = X.mean(axis = 1,keepdims =True)
print("M: \n", M)

X: 
 [[0.32717674 0.80124173 0.50329824 0.45091789 0.53169165 0.27209868
  0.16779681 0.98183034 0.0225719  0.01934472]
 [0.55040716 0.34367067 0.41306772 0.27008593 0.98651842 0.77827836
  0.83955945 0.09308709 0.87649232 0.50931701]
 [0.12059496 0.91448869 0.81960897 0.63899154 0.5689586  0.24800117
  0.22282189 0.17319343 0.16342691 0.63415148]
 [0.61301908 0.23895475 0.21486091 0.34275796 0.74397301 0.54889411
  0.20079087 0.16714288 0.37146538 0.37281738]
 [0.21562038 0.36720819 0.07945208 0.56181472 0.10745454 0.374334
  0.16908944 0.89900028 0.84786801 0.10212503]]
Y: 
 [[-0.08062013  0.39344486  0.09550137  0.04312102  0.12389478 -0.13569819
  -0.24000006  0.57403347 -0.38522497 -0.38845215]
 [-0.01564125 -0.22237775 -0.1529807  -0.29596248  0.42047001  0.21222995
   0.27351104 -0.47296132  0.31044391 -0.05673141]
 [-0.3298288   0.46406493  0.3691852   0.18856777  0.11853484 -0.20242259
  -0.22760187 -0.27723034 -0.28699685  0.18372771]
 [ 0.23155145 -0.14251289 -0.16660672 -0.

#### 59. How to sort an array by the nth column? (★★☆)

In [116]:
# DON'T UNDERSTAND
Z = np.random.randint(0,10,(5,5))
print(Z)

print(Z[(-Z)[:,1].argsort()])
print(Z[:,Z[1,:].argsort()])

[[1 0 7 8 8]
 [1 6 3 4 1]
 [5 6 3 2 9]
 [9 9 8 0 1]
 [5 7 4 2 0]]
[[9 9 8 0 1]
 [5 7 4 2 0]
 [1 6 3 4 1]
 [5 6 3 2 9]
 [1 0 7 8 8]]
[[1 8 7 8 0]
 [1 1 3 4 6]
 [5 9 3 2 6]
 [9 1 8 0 9]
 [5 0 4 2 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [125]:
Z = np.random.randint(0,3,(3,10))
print("Z: \n", Z)
Z[:,1] = 0
print("Z (new): \n", Z)
Z = Z.astype(bool)
print(Z)
print(~Z)
(Z).any(axis = 0)

Z: 
 [[0 2 0 0 0 2 0 2 1 1]
 [0 1 2 1 0 0 0 0 1 0]
 [0 0 1 2 0 1 2 0 0 1]]
Z (new): 
 [[0 0 0 0 0 2 0 2 1 1]
 [0 0 2 1 0 0 0 0 1 0]
 [0 0 1 2 0 1 2 0 0 1]]
[[False False False False False  True False  True  True  True]
 [False False  True  True False False False False  True False]
 [False False  True  True False  True  True False False  True]]
[[ True  True  True  True  True False  True False False False]
 [ True  True False False  True  True  True  True False  True]
 [ True  True False False  True False False  True  True False]]


array([False, False,  True,  True, False,  True,  True,  True,  True,
        True])

Save and commit your work.

In [126]:
import jovian

In [127]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "wasif1607/numpy-100-exercises" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/wasif1607/numpy-100-exercises


'https://jovian.com/wasif1607/numpy-100-exercises'

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [16]:
import jovian

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

In [18]:
import jovian

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [20]:
import jovian

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [22]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100